spring.cloud.stream.function.definition: httpSupplier|byteArrayTextToString
spring.cloud.stream.function.bindings.httpSupplier|byteArrayTextToString-out-0: user-regions

http.mapped-request-headers: username

spring.cloud.stream.bindings.user-regions.producer:
  useNativeEncoding: true
spring.cloud.stream.kafka.bindings.user-regions.producer:
  messageKeyExpression: headers['username']
  configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
  configuration.value.serializer: org.apache.kafka.common.serialization.StringSerializer

spring.main.web-application-type: reactive
spring.cloud.streamapp.security.enabled: false
spring.cloud.streamapp.security.csrf-enabled: false
#spring.cloud.stream.kafka.binder.configuration.key:
#  serializer: org.apache.kafka.common.serialization.StringSerializer
#spring.cloud.stream.kafka.binder.configuration.value:
#  serializer: org.apache.kafka.common.serialization.StringSerializer